manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: e41289566f3f58f89006ae15a62adb8812fdbe62
      import: true

  self:
    path: zephcore
