manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: e7c454caf8192d9063b7ce1ec8497a04d11e97de
      import: true

  self:
    path: zephcore
